export const deskConstants = {
    CREATE_DESK_REQUEST: 'CREATE_DESK_REQUEST',
    CREATE_DESK_SUCCESS: 'CREATE_DESK_SUCCESS',
    CREATE_DESK_FAILURE: 'CREATE_DESK_FAILURE',

    EDIT_DESK_REQUEST: 'EDIT_DESK_REQUEST',
    EDIT_DESK_SUCCESS: 'EDIT_DESK_SUCCESS',
    EDIT_DESK_FAILURE: 'EDIT_DESK_FAILURE',

    GET_CARDS_REQUEST: 'GET_CARDS_REQUEST',
    GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
    GET_CARDS_FAILURE: 'GET_CARDS_FAILURE',

    PIN_CARD_REQUEST: 'PIN_CARD_REQUEST',
    PIN_CARD_SUCCESS: 'PIN_CARD_SUCCESS',
    PIN_CARD_FAILURE: 'PIN_CARD_FAILURE',

    DELETE_CARD_REQUEST: 'DELETE_CARD_REQUEST',
    DELETE_CARD_SUCCESS: 'DELETE_CARD_SUCCESS',
    DELETE_CARD_FAILURE: 'DELETE_CARD_FAILURE',

    RECEIVE_CARD_FROM_SOCKET: 'RECEIVE_CARD_FROM_SOCKET',
    DELETE_CARD_FROM_SOCKET: 'DELETE_CARD_FROM_SOCKET',
};